# Generated by Django 4.2.7 on 2023-12-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Treasury",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10000)),
                ("giving", models.CharField(max_length=1000)),
                ("amount", models.FloatField()),
                ("phonenumber", models.CharField(max_length=20)),
                ("receipt_number", models.BigIntegerField(unique=True)),
                (
                    "receipt_url",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
            ],
        ),
    ]
