# Generated by Django 4.2.7 on 2023-12-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treasury",
            name="receipt_url",
            field=models.ImageField(blank=True, null=True, upload_to="receipts/"),
        ),
    ]
