# Generated by Django 4.2.7 on 2023-12-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_treasury_receipt_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treasury",
            name="receipt_url",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="home/ow3nso/projects/python/django/excel3/receipts/",
            ),
        ),
    ]
