# Generated by Django 4.2.7 on 2023-12-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_treasury_receipt_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treasury",
            name="receipt_url",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
