# Generated by Django 5.0.1 on 2024-01-08 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="process_statement",
            name="phonenumber",
        ),
        migrations.RemoveField(
            model_name="process_statement",
            name="receipt_number",
        ),
    ]
